from collections import namedtuple

ControllerConfig = namedtuple(
    "ControllerConfig",
    [
        "bone_name",
        "shape",
        "radius_multiplier",
        "offset_direction",
        "offset_multiplier",
        "shape_rotation_euler",
    ],
)

BONE_CONFIGS = [
    ControllerConfig(
        bone_name="Head",
        shape="CIRCLE",
        radius_multiplier=7.0,
        offset_direction=(0, -1, 0),
        offset_multiplier=5.0,
        shape_rotation_euler=(0, 0, 0),
    ),
    ControllerConfig(
        bone_name="Waist",
        shape="CIRCLE",
        radius_multiplier=2.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Hip",
        shape="SQUARE",
        radius_multiplier=5.0,
        offset_direction=(0, -1, -1),
        offset_multiplier=1.5,
        shape_rotation_euler="GLOBAL_HORIZONTAL",
    ),
    ControllerConfig(
        bone_name="Ear_01_R",
        shape="CIRCLE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ear_02_R",
        shape="CIRCLE",
        radius_multiplier=0.5,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ear_03_R",
        shape="CIRCLE",
        radius_multiplier=0.3,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ear_01_L",
        shape="CIRCLE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ear_02_L",
        shape="CIRCLE",
        radius_multiplier=0.5,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ear_03_L",
        shape="CIRCLE",
        radius_multiplier=0.3,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Shoulder_R",
        shape="CIRCLE",
        radius_multiplier=2,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Arm_R",
        shape="CIRCLE",
        radius_multiplier=1.5,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Elbow_R",
        shape="CIRCLE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Wrist_R",
        shape="CIRCLE",
        radius_multiplier=1.5,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Thumb_01_R",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Thumb_03_R",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Index_01_R",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Index_03_R",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ring_01_R",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ring_03_R",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Shoulder_L",
        shape="CIRCLE",
        radius_multiplier=2,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Arm_L",
        shape="CIRCLE",
        radius_multiplier=1.5,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Elbow_L",
        shape="CIRCLE",
        radius_multiplier=1,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Wrist_L",
        shape="CIRCLE",
        radius_multiplier=1.5,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Thumb_01_L",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Thumb_03_L",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Index_01_L",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Index_03_L",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ring_01_L",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ring_03_L",
        shape="SQUARE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Thigh_R",
        shape="CIRCLE",
        radius_multiplier=1.0,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Knee_R",
        shape="CIRCLE",
        radius_multiplier=0.8,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ankle_R",
        shape="CIRCLE",
        radius_multiplier=0.4,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Thigh_L",
        shape="CIRCLE",
        radius_multiplier=1,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Knee_L",
        shape="CIRCLE",
        radius_multiplier=0.8,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Ankle_L",
        shape="CIRCLE",
        radius_multiplier=0.4,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Sp_Hi_Tail0_B_00",
        shape="CIRCLE",
        radius_multiplier=1,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Sp_Hi_Tail0_B_01",
        shape="CIRCLE",
        radius_multiplier=0.8,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
    ControllerConfig(
        bone_name="Sp_Hi_Tail0_B_02",
        shape="CIRCLE",
        radius_multiplier=0.4,
        offset_direction=(0, 0, 0),
        offset_multiplier=0.0,
        shape_rotation_euler=(1.5708, 0, 0),
    ),
]
